Refactor
ArtiomTr/jest-coverage-report-action pull request #118
Opened 2021-07-22 20:19 UTC by ArtiomTr

2021-08-28 15:53 UTC, sidharthv96 commented on src/index.ts
> +        if (!isInitialized || isHeadCoverageGenerated) {
isHeadCoverageGenerated will be true even if a test fails, so this step will be skipped.

2021-08-28 15:55 UTC, sidharthv96 commented on src/index.ts
> +        if (!isInitialized || isHeadCoverageGenerated) {
https://github.com/sidharthv96/jest-coverage-report-action-test/pull/1/checks?check_run_id=3451046926#step:3:276

<img width="376" alt="image" src="https://user-images.githubusercontent.com/10703445/131223607-119a37ed-cbce-47da-a2b2-1ab258dcf654.png">

2021-08-28 19:49 UTC, sidharthv96 commented
<img width="504" alt="image" src="https://user-images.githubusercontent.com/10703445/131229399-4b2644ea-d042-43aa-946b-392e48698441.png">

This comes when a test run fails. 
I think we should handle that failure and not show "Unexpected error"

2021-08-29 13:25 UTC, ArtiomTr commented
@sidharthv96 Thank you for the review! I will consider all your remarks.

2021-09-21 15:08 UTC, sidharthv96 commented
Hey, any areas I could help to get this pushed out faster?
Happy to pitch in :)

2021-09-21 19:20 UTC, ArtiomTr commented
@sidharthv96, thank you for the initiative! As you can see, I have covered almost all of the files. There is only one file left untested - `run.ts`. It would be a huge help if you could write tests for this file. Thank you in advance.

2021-09-22 08:19 UTC, sidharthv96 commented
Added some tests in https://github.com/ArtiomTr/jest-coverage-report-action/pull/151

2021-09-23 13:27 UTC, ArtiomTr commented
@sidharthv96 thanks a lot! Your tests look good, only one small change is required.

2021-09-23 16:30 UTC, sidharthv96 requested changes
coverageFile and baseCoverageFile options are not being utilized presently.

2021-09-23 16:44 UTC, ArtiomTr commented
@sidharthv96, I think I will fix that in separate PR

2021-09-23 16:45 UTC, merged